<?php

return [
    'option_groups' => [
        [
            'code' => 'session_1_to_4',
            'name' => 'Session',
            'values' => ['Session 1', 'Session 2', 'Session 3', 'Session 4'],
        ],
        [
            'code' => 'session_1_to_6',
            'name' => 'Session',
            'values' => ['Session 1', 'Session 2', 'Session 3', 'Session 4', 'Session 5', 'Session 6'],
        ],
        [
            'code' => 'tirze_dosage',
            'name' => 'Dosage',
            'values' => ['2.5MG', '5MG', '7.5MG', '10MG', '12.5MG', '15MG'],
        ],
        [
            'code' => 'tirze_cycle',
            'name' => 'Treatment Stage',
            'values' => ['Session 1', 'Session 2', 'Session 3', 'Session 4', 'Maintenance 1', 'Maintenance 2', 'Maintenance 3', 'Maintenance 4'],
        ],
        [
            'code' => 'promo_flow',
            'name' => 'Flow',
            'values' => ['Promo TT', 'Package', 'Prep', '1st Trial', '2nd Visit'],
        ],
        [
            'code' => 'medex_body_area',
            'name' => 'Body Area',
            'values' => ['Tummy', 'Hand', 'Thigh'],
        ],
        [
            'code' => 'aqualyx_area',
            'name' => 'Treatment Area',
            'values' => ['Double Chin', 'Hand', 'Tummy'],
        ],
        [
            'code' => 'eyesfix_flow',
            'name' => 'Flow',
            'values' => ['Promo TT', 'Package'],
        ],
    ],
    'staff' => [
        [
            'full_name' => 'Dr. Amanda Binti Elli',
            'job_title' => 'Medical Officer',
            'department' => 'Medical',
            'operational_role' => 'doctor',
        ],
        [
            'full_name' => 'Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad',
            'job_title' => 'Medical Officer',
            'department' => 'Medical',
            'operational_role' => 'doctor',
        ],
        [
            'full_name' => 'Nur Adilla Binti Mohd Ali',
            'job_title' => 'Nurse Assistant',
            'department' => 'Medical',
            'operational_role' => 'nurse',
        ],
        [
            'full_name' => 'Nur Farhanna Binti Abdul Malek',
            'job_title' => 'Beautician',
            'department' => 'Beauty & Aesthetic',
            'operational_role' => 'beautician',
        ],
        [
            'full_name' => 'Emma',
            'job_title' => 'Beautician',
            'department' => 'Beauty & Aesthetic',
            'operational_role' => 'beautician',
        ],
        [
            'full_name' => 'Sora',
            'job_title' => 'Manicurist',
            'department' => 'Spa',
            'operational_role' => 'manicurist',
        ],
        [
            'full_name' => 'Monica Tial Tin Rem',
            'job_title' => 'Nail Artist',
            'department' => 'Spa',
            'operational_role' => 'manicurist',
        ],
    ],
    'retired_service_codes' => [
        'consult_tirze_2_5mg',
        'consult_tirze_5mg',
        'consult_tirze_7_5mg',
        'consult_tirze_10mg',
        'consult_tirze_12_5mg',
        'consult_tirze_15mg',
    ],
    'services' => [
        ['code' => 'wellness_exosome_drip', 'name' => 'Exosome Drip', 'category_key' => 'wellness', 'default_staff_role' => 'doctor', 'option_groups' => [], 'staff' => ['Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad']],
        ['code' => 'wellness_liver_detox_madani', 'name' => 'Liver Detox for Madani', 'category_key' => 'wellness', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_4'], 'staff' => ['Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad']],
        ['code' => 'wellness_blood_test', 'name' => 'Blood Test', 'category_key' => 'wellness', 'default_staff_role' => 'doctor', 'option_groups' => [], 'staff' => ['Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad']],
        ['code' => 'wellness_nad_drip', 'name' => 'NAD+ Drip', 'category_key' => 'wellness', 'default_staff_role' => 'doctor', 'option_groups' => [], 'staff' => ['Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad']],
        ['code' => 'wellness_bbs_review', 'name' => 'BBS Review', 'category_key' => 'wellness', 'default_staff_role' => 'doctor', 'option_groups' => [], 'staff' => ['Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad']],
        ['code' => 'wellness_liver_detox_infusion', 'name' => 'Liver Detox Infusion', 'category_key' => 'wellness', 'default_staff_role' => 'doctor', 'option_groups' => [], 'staff' => ['Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad']],
        ['code' => 'wellness_liver_detox_bmi', 'name' => 'Liver Detox BMI', 'category_key' => 'wellness', 'default_staff_role' => 'doctor', 'option_groups' => [], 'staff' => ['Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad']],
        ['code' => 'consult_tirze', 'name' => 'Tirze', 'category_key' => 'consultations', 'consultation_category_key' => 'wellness', 'default_staff_role' => 'doctor', 'option_groups' => ['tirze_dosage', 'tirze_cycle'], 'staff' => ['Dr. Syarifah Munira \'Aaqilah Binti Al Sayed Mohamad']],
        ['code' => 'tirze_2_5mg', 'name' => 'Tirze 2.5MG', 'category_key' => 'wellness', 'default_staff_role' => 'nurse', 'option_groups' => ['tirze_cycle'], 'staff' => ['Nur Adilla Binti Mohd Ali']],
        ['code' => 'tirze_5mg', 'name' => 'Tirze 5MG', 'category_key' => 'wellness', 'default_staff_role' => 'nurse', 'option_groups' => ['tirze_cycle'], 'staff' => ['Nur Adilla Binti Mohd Ali']],
        ['code' => 'tirze_7_5mg', 'name' => 'Tirze 7.5MG', 'category_key' => 'wellness', 'default_staff_role' => 'nurse', 'option_groups' => ['tirze_cycle'], 'staff' => ['Nur Adilla Binti Mohd Ali']],
        ['code' => 'tirze_10mg', 'name' => 'Tirze 10MG', 'category_key' => 'wellness', 'default_staff_role' => 'nurse', 'option_groups' => ['tirze_cycle'], 'staff' => ['Nur Adilla Binti Mohd Ali']],
        ['code' => 'tirze_12_5mg', 'name' => 'Tirze 12.5MG', 'category_key' => 'wellness', 'default_staff_role' => 'nurse', 'option_groups' => ['tirze_cycle'], 'staff' => ['Nur Adilla Binti Mohd Ali']],
        ['code' => 'tirze_15mg', 'name' => 'Tirze 15MG', 'category_key' => 'wellness', 'default_staff_role' => 'nurse', 'option_groups' => ['tirze_cycle'], 'staff' => ['Nur Adilla Binti Mohd Ali']],
        ['code' => 'aesthetic_profhilo', 'name' => 'Profhilo', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_ha_skinbooster', 'name' => 'HA Skinbooster', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_dermal_e_sign', 'name' => 'Dermal E Sign', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_revok_50', 'name' => 'Revok-50', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_rejuran', 'name' => 'Rejuran', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_resttlane', 'name' => 'Resttlane', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_chemical_peel', 'name' => 'Chemical Peel', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_microneedling', 'name' => 'Microneedling', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_hair_exosome', 'name' => 'Hair Exosome', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_face_exosome', 'name' => 'Face Exosome', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_hair_prp', 'name' => 'Hair PRP', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_face_prp', 'name' => 'Face PRP', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_aqualyx', 'name' => 'Aqualyx', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['aqualyx_area'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_subcision', 'name' => 'Subcision', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_brightening_5x_peels', 'name' => 'Brightening 5X Peels', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_melano_out', 'name' => 'Melano-Out', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_botox', 'name' => 'Botox', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'aesthetic_acne_treatment', 'name' => 'Acne Treatment', 'category_key' => 'aesthetics', 'default_staff_role' => 'doctor', 'option_groups' => ['session_1_to_6'], 'staff' => ['Dr. Amanda Binti Elli']],
        ['code' => 'beauty_medex_full_face_lifting', 'name' => 'Medex Full Face Lifting', 'category_key' => 'spa', 'default_staff_role' => 'beautician', 'option_groups' => ['promo_flow'], 'staff' => ['Nur Farhanna Binti Abdul Malek', 'Emma']],
        ['code' => 'beauty_medex_body', 'name' => 'Medex Body', 'category_key' => 'spa', 'default_staff_role' => 'beautician', 'option_groups' => ['medex_body_area'], 'staff' => ['Nur Farhanna Binti Abdul Malek', 'Emma']],
        ['code' => 'beauty_medex_eyesfix_facial', 'name' => 'Medex Eyesfix Facial', 'category_key' => 'spa', 'default_staff_role' => 'beautician', 'option_groups' => ['eyesfix_flow'], 'staff' => ['Nur Farhanna Binti Abdul Malek', 'Emma']],
        ['code' => 'beauty_oxyglow_facial', 'name' => 'Oxyglow Facial', 'category_key' => 'spa', 'default_staff_role' => 'beautician', 'option_groups' => ['promo_flow'], 'staff' => ['Nur Farhanna Binti Abdul Malek', 'Emma']],
        ['code' => 'beauty_microneedling_rejuvenation', 'name' => 'Microneedling Rejuvenation', 'category_key' => 'spa', 'default_staff_role' => 'beautician', 'option_groups' => ['promo_flow'], 'staff' => ['Nur Farhanna Binti Abdul Malek', 'Emma']],
        ['code' => 'beauty_prep_assist_doctor', 'name' => 'Prep & Assist Doctor', 'category_key' => 'spa', 'default_staff_role' => 'beautician', 'option_groups' => ['promo_flow'], 'staff' => ['Nur Farhanna Binti Abdul Malek', 'Emma']],
        ['code' => 'spa_classic_manicure', 'name' => 'Classic Manicure', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_classic_pedicure', 'name' => 'Classic Pedicure', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_spa_manicure', 'name' => 'Spa Manicure', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_spa_pedicure', 'name' => 'Spa Pedicure', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_eyelash_extention', 'name' => 'Eyelash Extention', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_spa_callus', 'name' => 'Spa Callus', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_breathable_nail_gel', 'name' => 'Breathable Nail Gel', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_signature_spa_ritual', 'name' => 'Signature Spa Ritual', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_classic_mani_pedi', 'name' => 'Classic Manicure + Pedicure', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_brightening_peel', 'name' => 'Brightening Peel', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => ['promo_flow'], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
        ['code' => 'spa_footbath', 'name' => 'Footbath', 'category_key' => 'spa', 'default_staff_role' => 'manicurist', 'option_groups' => [], 'staff' => ['Sora', 'Monica Tial Tin Rem']],
    ],
];
